"""Validate copied original chunk identities; generated bytes are not an oracle."""
from pathlib import Path
import hashlib
import json
import struct
import subprocess
import sys
import tempfile
from types import SimpleNamespace
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from capture_gb10_mtp_chunked_prefill import (
    FRONTIERS, LOGITS_PROCESSOR_SHA, MAXIMUM_BYTES, chunk_layout,
    observe_original_prefill_logits, qualify_chunked_prefill_capture)


class MtpChunkedPrefillCaptureTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.prompt, self.outputs = [10, 11, 12, 13, 14, 15, 16], [21, 22]
        self.transactions, selected, chunks = [], {}, {}
        for ordinal, (first, count) in enumerate(((0, 3), (3, 4))):
            discarded = first + count < len(self.prompt)
            ids = self.prompt[first + 1:first + count] + [self.prompt[-1] if discarded else self.outputs[0]]
            rows = [dict(row=i, position=first + i, input_token_id=ids[i]) for i in (0, count - 1)]
            transaction = dict(ordinal=ordinal, first_position=first, token_count=count,
                discarded_target=discarded, rows=rows, sampled_rows=[count - 1],
                original_result_returned_unchanged=True, draft_token_ids=[[42]])
            self.transactions.append(transaction)
            chunk = dict(transaction=ordinal, first_position=first, rows=count,
                bytes=chunk_layout(len(self.prompt), transaction), files={},
                shifted_input_ids=self.save(f'ids-{ordinal}', struct.pack('<' + str(count) + 'I', *ids), [count], 'torch.int32'))
            for label, width in FRONTIERS.items():
                values = [struct.pack('<' + str(width) + 'H', *((ordinal * 47 + row * 97 + i) % 65536 for i in range(width)))
                          for row in range(count)]
                chunk['files'][label] = self.save(f'full-{ordinal}-{label}', b''.join(values), [count, width])
                selected[f'{ordinal}-{label}'] = dict(self.save(f'selected-{ordinal}-{label}',
                    b''.join(values[row['row']] for row in rows), [2, width]), transaction=ordinal, label=label)
            chunks[str(ordinal)] = chunk
        hidden = b'\x80\x3f' * 2048
        selected['1-final-norm'] = dict(self.save('selected-1-final-norm', hidden * 2, [2, 2048]), transaction=1, label='final-norm')
        logits = bytearray(248320 * 2);struct.pack_into('<H', logits, 42 * 2, 0x4000)
        draft = dict(transaction=1, sampled_row=3, original_result_returned_unchanged=True,
            hidden=self.save('draft-hidden', hidden, [1, 2048]), logits=self.save('draft-logits', logits, [1, 248320]))
        self.full = dict(chunks=chunks, final_draft=draft, prompt_tokens=len(self.prompt),
            bytes=sum(row['bytes'] for row in chunks.values()) + 4096 + 248320 * 2,
            logits_processor_source=dict(sha256=LOGITS_PROCESSOR_SHA), original_results_returned_unchanged=True)
        self.worker = dict(mtp_chunked_prefill=self.full,
            mtp_boundaries=dict(transactions=self.transactions, files=selected, original_history_qualified=True))

    def save(self, name, data, shape, dtype='torch.bfloat16'):
        path = self.root / (name + '.bin');path.write_bytes(data)
        return dict(file=path.name, bytes=len(data), sha256=hashlib.sha256(data).hexdigest(), shape=shape, dtype=dtype)

    def qualify(self):
        qualify_chunked_prefill_capture(self.worker, self.prompt, self.outputs, self.root)

    def alter(self, meta, offset, rehash=True):
        path = self.root / meta['file'];data = bytearray(path.read_bytes());data[offset] ^= 1;path.write_bytes(data)
        if rehash:meta['sha256'] = hashlib.sha256(data).hexdigest()

    def test_complete_chunk_shifts_frontiers_and_final_draft(self):
        self.qualify()
        self.assertTrue(self.full['original_chunk_frontiers_qualified'])
        self.assertEqual(self.full['selected_observation_rows_compared'], 12)
        self.assertEqual((self.full['final_draft_token'], self.full['final_draft_logit']), (42, 2.0))

    def test_layout_bound_and_discard_contract(self):
        self.assertLess(32768 * 6148 + 4096 + 248320 * 2, MAXIMUM_BYTES)
        for prompt, updates in ((0, {}), (32769, {}), (True, {}), (7, {'token_count': 8193}),
                (7, {'discarded_target': False}), (7, {'first_position': 6}), (7, {'first_position': True})):
            with self.subTest(prompt=prompt, updates=updates), self.assertRaises(ValueError):
                chunk_layout(prompt, dict(self.transactions[0], **updates))

    def test_discarded_backup_uses_complete_prompt_last_token(self):
        self.alter(self.full['chunks']['0']['shifted_input_ids'], 8)
        with self.assertRaisesRegex(ValueError, 'chunk shift'):
            self.qualify()

    def test_missing_chunk_and_changed_order_fail(self):
        chunk = self.full['chunks'].pop('1')
        with self.assertRaisesRegex(ValueError, 'missing or extra'):
            self.qualify()
        self.full['chunks']['1'] = chunk;self.transactions.reverse()
        with self.assertRaisesRegex(ValueError, 'ordered prompt'):
            self.qualify()

    def test_full_unsampled_tensor_hash_is_checked(self):
        self.alter(self.full['chunks']['0']['files']['target-hidden'], 4096, False)
        with self.assertRaisesRegex(ValueError, 'file identity'):
            self.qualify()

    def test_full_and_selected_original_values_must_match(self):
        self.alter(self.full['chunks']['1']['files']['k-rope'], 0)
        with self.assertRaisesRegex(ValueError, 'selected observations differ'):
            self.qualify()

    def test_final_hidden_binds_sampled_original_norm(self):
        self.alter(self.full['final_draft']['hidden'], 0)
        with self.assertRaisesRegex(ValueError, 'sampled norm row'):
            self.qualify()

    def test_final_logits_bind_actual_original_draft(self):
        self.transactions[-1]['draft_token_ids'] = [[43]]
        with self.assertRaisesRegex(ValueError, 'final sample'):
            self.qualify()

    def test_source_and_byte_ledger_are_checked(self):
        self.full['bytes'] += 2
        with self.assertRaisesRegex(ValueError, 'byte accounting'):
            self.qualify()
        self.full['bytes'] -= 2;self.full['logits_processor_source']['sha256'] = '0' * 64
        with self.assertRaisesRegex(ValueError, 'incomplete original'):
            self.qualify()

    def test_original_logit_call_and_object_return_are_preserved(self):
        hidden = SimpleNamespace(shape=(1, 2048), dtype='torch.bfloat16')
        result = SimpleNamespace(shape=(1, 248320), dtype='torch.bfloat16')
        calls, observed = [], []
        def original(*args, **kwargs):
            calls.append((args, kwargs));return result
        def observe(*args):observed.append(args)
        for transaction in (None, self.transactions[0], self.transactions[-1],
                dict(self.transactions[-1], first_position=7, token_count=2)):
            self.assertIs(observe_original_prefill_logits(original, transaction, 7, observe, hidden), result)
        self.assertEqual(len(calls), 4);self.assertEqual(len(observed), 1)
        self.assertIs(observed[0][1], hidden);self.assertIs(observed[0][2], result)

    def test_capture_cli_keeps_controls_and_enforces_explicit_mode_bound(self):
        additional = self.root / 'cases.json'
        additional.write_text(json.dumps([dict(name='cold-chunks-out32', prompt_token_ids=[42] * 17408, output_count=32)]))
        output = self.root / 'capture'
        command = [sys.executable, str(ROOT / 'scripts/capture_gb10_token_matrix.py'),
            '--oracle-q7169', str(ROOT / 'contracts/arbitrary_q7169_gb10_oracle.json'),
            '--oracle-q8192', str(ROOT / 'contracts/hprefill_q8192_gb10_oracle.json'),
            '--runtime-boundaries', '--mtp-boundaries', '--mtp-kernel-launches', '--mtp-chunked-prefill-frontiers',
            '--additional-cases', str(additional), '--maximum-prompt-tokens', '33792',
            '--source-commit', '0' * 40, '--output-dir', str(output)]
        run = subprocess.run(command, capture_output=True, text=True, timeout=10)
        self.assertEqual(run.returncode, 0, run.stderr)
        record = json.loads((output / 'capture.json').read_text())
        self.assertTrue(record['mtp_chunked_prefill_frontiers'])
        self.assertFalse(record['completed']);self.assertFalse(record['windows_acceptance'])
        self.assertEqual([row['name'] for row in record['fixtures']], ['q7169-out32', 'q8192-out32', 'cold-chunks-out32'])
        rejected = self.root / 'rejected'
        command[-1] = str(rejected)
        invalid_mode = command + ['--mtp-full-prefill-frontiers']
        self.assertNotEqual(subprocess.run(invalid_mode, capture_output=True, text=True, timeout=10).returncode, 0)
        additional.write_text(json.dumps([dict(name='too-long', prompt_token_ids=[42] * 33792, output_count=32)]))
        run = subprocess.run(command, capture_output=True, text=True, timeout=10)
        self.assertNotEqual(run.returncode, 0)
        self.assertIn('at most 32768 actual prompt tokens', run.stderr)
        self.assertFalse(rejected.exists())


if __name__ == '__main__':
    unittest.main()
