#!/usr/bin/env python3
"""Compile explicit-layout ordered GDN for gfx1151, without a GPU.

Triton 3.6.0 is a build dependency only. Embedded code objects require their
own AMD numerical and real-model qualification; compilation is not acceptance.
"""
from pathlib import Path
import argparse
import hashlib
import json
import os
import re
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
STAGES = ("kkt", "inverse", "w", "u", "scores", "residual", "state", "output")


def jobs():
    sys.path.insert(0, str(ROOT / "native/providers/gdn"))
    sys.path.insert(0, str(ROOT / "native/providers/gdn_explicit_layout"))
    import ordered_pipeline as pipeline
    from ordered_inverse import native_ordered_64_inverse_kernel
    from ordered_pipeline import integer_u_kernel
    common = dict(BM=8, BN=8)
    gram = dict(Q="*bf16", K="*bf16", Beta="*fp32", G="*fp32", Table="*u8")
    return [
        ("kkt", pipeline.gram_kernel, dict(**gram, Out="*fp32", T="i32"), dict(**common, SCORE=False)),
        ("inverse", native_ordered_64_inverse_kernel, dict(A="*fp32", Ai="*bf16", T="i32"),
         dict(cu_seqlens=None, chunk_indices=None, H=32, BT=64, USE_TMA=False,
              IS_VARLEN=False, DOT_PRECISION="ieee")),
        ("w", pipeline.w_kernel,
         dict(A="*bf16", K="*bf16", Beta="*fp32", G="*fp32", Table="*u8", W="*bf16", T="i32"), common),
        ("u", integer_u_kernel,
         dict(A="*bf16", V="*bf16", Beta="*fp32", U="*bf16", Debug="*fp32", T="i32"),
         dict(H=32, NV=128, **common, CAPTURE_F32=False)),
        ("scores", pipeline.gram_kernel, dict(**gram, Out="*bf16", T="i32"), dict(**common, SCORE=True)),
        ("residual", pipeline.residual_kernel,
         dict(W="*bf16", U="*bf16", H0="*fp32", G="*fp32", Table="*u8", VNew="*bf16", Residual="*bf16", T="i32"), common),
        ("state", pipeline.state_kernel,
         dict(K="*bf16", Residual="*bf16", H0="*fp32", G="*fp32", Table="*u8", Final="*fp32", T="i32"), common),
        ("output", pipeline.output_kernel,
         dict(Q="*bf16", VNew="*bf16", H0="*fp32", G="*fp32", Scores="*bf16", Table="*u8", Out="*bf16", T="i32"), common),
    ]


def embed(out, compiled):
    lines = ["// Generated by tools/compile_linux_core_gdn_explicit.py.",
             "// Experimental gfx1151 images; retain the bundled arithmetic/license notices.",
             "// No runtime Python dependency. Native qualification remains required.",
             "enum class OrderedStage : unsigned { Kkt, Inverse, W, U, Scores, Residual, State, Output, Count };",
             "struct OrderedImage { const unsigned char* data; std::size_t bytes;",
             "  const char* sha256; const char* name; unsigned warps, shared; };"]
    for name in STAGES:
        data = (out / compiled[name]["file"]).read_bytes()
        lines.append("alignas(256) static const unsigned char ordered_" + name + "_image[] = {")
        lines += ["  " + ", ".join("0x%02x" % v for v in data[i:i + 16]) + ","
                  for i in range(0, len(data), 16)]
        lines.append("};")
    lines.append("static const OrderedImage ordered_images[] = {")
    for name in STAGES:
        item = compiled[name]
        meta = item["metadata"]
        lines.append('  {ordered_%s_image, sizeof(ordered_%s_image), "%s", "%s", %d, %d},' %
                     (name, name, item["sha256"], meta["name"], meta["num_warps"], meta["shared"]))
    lines += ["};", "static_assert(sizeof(ordered_images) / sizeof(ordered_images[0]) ==",
              "              static_cast<unsigned>(OrderedStage::Count));"]
    path = out / "gb10_gdn_ordered_images.inc"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    for name in ("CUDA_VISIBLE_DEVICES", "HIP_VISIBLE_DEVICES", "ROCR_VISIBLE_DEVICES"):
        if os.environ.get(name) != "-1":
            raise ValueError("Offline compilation requires " + name + "=-1")
    import triton
    from triton.backends.compiler import GPUTarget
    from triton.compiler import ASTSource
    from triton.experimental.gluon._runtime import GluonASTSource
    if triton.__version__ != "3.6.0":
        raise ValueError("The pinned Triton 3.6.0 compiler is required")
    out = args.out.resolve()
    out.mkdir(parents=True, exist_ok=False)
    started = time.monotonic()
    options = dict(num_warps=4, num_stages=2, enable_fp_fusion=False)
    compiled = {}
    for name, fn, signature, constants in jobs():
        start = time.monotonic()
        source_type = ASTSource if name == "inverse" else GluonASTSource
        kernel = triton.compile(source_type(fn, signature=signature, constexprs=constants),
                                target=GPUTarget("hip", "gfx1151", 32), options=options)
        data = kernel.asm["hsaco"]
        image = out / (name + ".hsaco")
        image.write_bytes(data)
        assembly = kernel.asm["amdgcn"]
        (out / (name + ".amdgcn")).write_text(assembly, encoding="utf-8")
        resources = {key: re.findall(re.escape(key) + r"\s*:?\s*(\d+)", assembly)
                     for key in (".vgpr_count", ".vgpr_spill_count", ".private_segment_fixed_size")}
        compiled[name] = dict(file=image.name, bytes=len(data), sha256=hashlib.sha256(data).hexdigest(),
                             kernel_hash=kernel.hash, metadata=kernel.metadata._asdict(),
                             signature=signature, constants=constants, options=options,
                             resources=resources, compile_seconds=time.monotonic() - start)
    include = embed(out, compiled)
    sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
    sources = [ROOT / "native/providers/gdn_explicit_layout" / name for name in
               ("ordered_pipeline.py", "group16.py", "exp2.py")]
    sources.append(ROOT / "native/providers/gdn/ordered_inverse.py")
    report = dict(source_files={p.relative_to(ROOT).as_posix(): sha(p) for p in sources},
                  compiler_script_sha256=sha(Path(__file__)), triton_version=triton.__version__,
                  compiled=compiled, embedded_image_sha256=sha(include), embedded_image_bytes=include.stat().st_size,
                  wall_seconds=time.monotonic() - started, cpu_only=True, gpu_executed=False,
                  inference_acceptance=False, performance_acceptance=False)
    (out / "result.json").write_text(json.dumps(report, indent=2, default=str) + "\n", encoding="utf-8")
    print(json.dumps(dict(compiled=len(compiled), embedded_image_sha256=sha(include),
                         resources={k: v["resources"] for k, v in compiled.items()})))


if __name__ == "__main__":
    main()
