#!/usr/bin/env python3
"""Offline build of the optional original64 preparation and fused recurrence."""
from pathlib import Path
import argparse
import hashlib
import importlib.util
import json
import os
import re
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
STAGES = ('kkt', 'inverse', 'w', 'u', 'scores', 'recurrence')


def jobs():
    directory = ROOT/'native/providers/gdn_persistent'
    def module(name, path):
        spec = importlib.util.spec_from_file_location(name, path)
        result = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(result)
        return result
    previous = {name:sys.modules.get(name) for name in ('integer_u','ordered_pipeline','group16','exp2')}
    try:
        arithmetic = module('persistent_upstream_u64', directory/'upstream/integer_u.py')
        sys.modules['integer_u'] = arithmetic
        upstream = module('persistent_upstream_pipeline', directory/'upstream/ordered_pipeline.py')
        inverse = module('persistent_upstream_inverse', directory/'upstream/ordered_inverse.py')
        sys.modules['group16'] = module('persistent_group16', directory/'group16.py')
        sys.modules['exp2'] = module('persistent_exp2', directory/'exp2.py')
        sys.modules['ordered_pipeline'] = module('persistent_axes', directory/'ordered_pipeline.py')
        recurrence = module('persistent_recurrence', directory/'persistent.py')
    finally:
        for name, value in previous.items():
            if value is None: sys.modules.pop(name, None)
            else: sys.modules[name] = value
    common = dict(BM=8,BN=8)
    gram = dict(Q='*bf16',K='*bf16',Beta='*fp32',G='*fp32',Table='*u8')
    return [
        ('kkt', upstream.gram_kernel, dict(**gram,Out='*fp32',T='i32'), dict(**common,SCORE=False), False),
        ('inverse', inverse.native_ordered_64_inverse_kernel, dict(A='*fp32',Ai='*bf16',T='i32'),
         dict(cu_seqlens=None,chunk_indices=None,H=32,BT=64,USE_TMA=False,IS_VARLEN=False,DOT_PRECISION='ieee'), False),
        ('w', upstream.w_kernel, dict(A='*bf16',K='*bf16',Beta='*fp32',G='*fp32',Table='*u8',W='*bf16',T='i32'), common, False),
        ('u', arithmetic.integer_u_kernel, dict(A='*bf16',V='*bf16',Beta='*fp32',U='*bf16',Debug='*fp32',T='i32'),
         dict(H=32,NV=128,**common,CAPTURE_F32=False), False),
        ('scores', upstream.gram_kernel, dict(**gram,Out='*bf16',T='i32'), dict(**common,SCORE=True), False),
        ('recurrence', recurrence.persistent_kernel,
         dict(Q='*bf16',K='*bf16',W='*bf16',U='*bf16',G='*fp32',Scores='*bf16',Table='*i8',Initial='*fp32',
              Final='*fp32',Out='*bf16',VNew='*bf16',Checkpoints='*bf16',T='i32'), dict(CAPTURE=False), True),
    ]


def embed(out, compiled):
    lines = ['// Generated by tools/compile_linux_core_gdn_persistent.py.',
        '// Original64 upstream and explicit persistent recurrence; default off.',
        '// Build-time Triton only; no runtime Python dependency.',
        'enum class PersistentStage : unsigned { Kkt, Inverse, W, U, Scores, Recurrence, Count };',
        'struct PersistentImage { const unsigned char* data; std::size_t bytes;',
        '  const char* sha256; const char* name; unsigned warps, shared; };']
    for name in STAGES:
        data = (out/compiled[name]['file']).read_bytes()
        lines.append('alignas(256) static const unsigned char persistent_'+name+'_image[] = {')
        lines.extend('  '+', '.join('0x%02x'%v for v in data[i:i+16])+',' for i in range(0,len(data),16))
        lines.append('};')
    lines.append('static const PersistentImage persistent_images[] = {')
    for name in STAGES:
        entry = compiled[name]; meta=entry['metadata']
        lines.append('  {persistent_%s_image, sizeof(persistent_%s_image), "%s", "%s", %d, %d},'%
            (name,name,entry['sha256'],meta['name'],meta['num_warps'],meta['shared']))
    lines.extend(['};','static_assert(sizeof(persistent_images) / sizeof(persistent_images[0]) ==',
        '              static_cast<unsigned>(PersistentStage::Count));'])
    path = out/'gb10_gdn_persistent_images.inc'
    path.write_text('\n'.join(lines)+'\n')
    return path


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out',type=Path,required=True)
    args=parser.parse_args()
    for name in ('CUDA_VISIBLE_DEVICES','HIP_VISIBLE_DEVICES','ROCR_VISIBLE_DEVICES'):
        if os.environ.get(name)!='-1': raise ValueError(name+'=-1 is required for offline compilation')
    import triton
    from triton.compiler import ASTSource
    from triton.backends.compiler import GPUTarget
    from triton.experimental.gluon._runtime import GluonASTSource
    assert triton.__version__=='3.6.0'
    out=args.out.resolve();out.mkdir(parents=True,exist_ok=False)
    started=time.monotonic();compiled={}
    for name,fn,signature,constants,gluon in jobs():
        options=dict(num_warps=4,num_stages=2,enable_fp_fusion=False)
        source=GluonASTSource if gluon else ASTSource
        kernel=triton.compile(source(fn,signature=signature,constexprs=constants),
            target=GPUTarget('hip','gfx1151',32),options=options)
        path=out/(name+'.hsaco');path.write_bytes(kernel.asm['hsaco'])
        for kind in ('amdgcn','llir'):(out/(name+'.'+kind)).write_text(kernel.asm[kind])
        resources={key:re.findall(re.escape(key)+r'\s*:?\s*(\d+)',kernel.asm['amdgcn'])
            for key in ('.vgpr_count','.vgpr_spill_count','.private_segment_fixed_size')}
        compiled[name]=dict(file=path.name,bytes=path.stat().st_size,sha256=hashlib.sha256(path.read_bytes()).hexdigest(),
            metadata=kernel.metadata._asdict(),signature=signature,constants=constants,options=options,resources=resources)
    include=embed(out,compiled)
    sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
    files=sorted((ROOT/'native/providers/gdn_persistent').rglob('*.py'))
    report=dict(compiled=compiled,source_files={str(p.relative_to(ROOT)):sha(p)for p in files},
        compiler_sha256=sha(Path(__file__)),embedded_include_sha256=sha(include),
        cpu_only=True,gpu_executed=False,wall_seconds=time.monotonic()-started,
        inference_acceptance=False,performance_acceptance=False)
    (out/'result.json').write_text(json.dumps(report,indent=2,default=str)+'\n')
    print(json.dumps(dict(images=len(compiled),embedded_include_sha256=sha(include))))


if __name__=='__main__': main()
